services:
#   minio:
#     build:
#         context: .
#         dockerfile: minio.dockerfile
#     environment:
#         MINIO_ROOT_USER: "${MINIO_USERNAME}"
#         MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
#         MINIO_PORT: "${MINIO_PORT}"
#         MINIO_CONSOLE_PORT: "${MINIO_CONSOLE_PORT}"
#     networks:
#         - healthcare
#     ports:
#         - "9000:${MINIO_PORT}"
#         - "9001:${MINIO_CONSOLE_PORT}"
#   mongodb:
#     build:
#         context: .
#         dockerfile: mongodb.dockerfile
#     networks:
#         - healthcare
#     ports:
#         - "27017:${MONGODB_PORT}"
  reactjs:
    build:
        context: .
        dockerfile: reactjs.dockerfile
    environment:
        MINIO_IP: ${MINIO_IP}
        MINIO_PORT: ${MINIO_PORT}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
        MINIO_ACCESS_SECRET: ${MINIO_ACCESS_SECRET}
        HOST_IP: ${HOST_IP}
        HOST_PORT: ${REACT_PORT}
        FLASK_IP: ${FLASK_IP}
        FLASK_PORT: ${FLASK_PORT}
        NODE_IP : ${NODE_IP}
        NODE_PORT : ${NODE_PORT}
        REACT_IP: ${REACT_IP}
        REACT_PORT: ${REACT_PORT}
    networks:
        - healthcare
    ports:
        - "7171:${REACT_PORT}"
  nodejs:
    build:
        context: .
        dockerfile: nodejs.dockerfile
    environment:
        NODE_IP : ${NODE_IP}
        NODE_PORT : ${NODE_PORT}
        MONDODB_ATLAS_URI_DEPLOY : ${MONGODB_URL}
        MONDODB_ATLAS_URI_DEV : ${MONGODB_URL}
        APP_URL_DEPLOY: "http://${HOST_IP}:${REACT_PORT}"
        APP_URL_DEV: "http://${HOST_IP}:${REACT_PORT}"
        PORT_DEV: ${NODE_PORT}
        PORT_DEPLOY: ${NODE_PORT}
    networks:
        - healthcare
    ports:
        - "4000:${NODE_PORT}"
    # extra_hosts:
    #     - "mongoservice:172.17.0.1"
  flask:
    build:
        context: .
        dockerfile: flask.dockerfile
    networks:
        - healthcare
    ports:
        - "6500:${FLASK_PORT}"

networks:
  healthcare:
