services:
    reactjs:
        build:
            context: .
            dockerfile: reactjs.dockerfile
        environment:
            REACT_APP_DEV: ${DEV}
            REACT_APP_URL_PREFIX_DEV: ${REACT_APP_URL_PREFIX_DEV}
            REACT_APP_URL_PREFIX_PROD: ${REACT_APP_URL_PREFIX_PROD}
            REACT_APP_PROXY_DEV: ${REACT_APP_PROXY_DEV}
            REACT_APP_PROXY_DEPLOY: ${REACT_APP_PROXY_DEPLOY}
            REACT_APP_FLASK_URL_DEV: ${REACT_APP_FLASK_URL_DEV}
            REACT_APP_FLASK_URL_PROD: ${REACT_APP_FLASK_URL_PROD}
            PORT: ${REACT_PORT}
        networks:
            - healthcare
        ports:
            - "${REACT_PORT}:${REACT_PORT}"
    nodejs:
        build:
            context: .
            dockerfile: nodejs.dockerfile
        environment:
            DEV: ${DEV}
            APP_URL_DEV: ${CORS_HOST}
            APP_URL_PROD: ${CORS_HOST}
            MONDODB_URL_DEV: ${MONGODB_URL_DEV}
            MONDODB_URL_PROD: ${MONGODB_URL_PROD}
            NODE_PORT_DEV: ${NODE_PORT_DEV}
            NODE_PORT_PROD: ${NODE_PORT_PROD}
        networks:
            - healthcare
        ports:
            - "4000:${NODE_PORT}"
    flask:
        environment:
            DEV: ${DEV}
            MINIO_ACCESS_KEY_DEV: ${MINIO_ACCESS_KEY_DEV}
            MINIO_ACCESS_SECRET_DEV: ${MINIO_ACCESS_SECRET_DEV}
            MINIO_ACCESS_KEY_PROD: ${MINIO_ACCESS_KEY_PROD}
            MINIO_ACCESS_SECRET_PROD: ${MINIO_ACCESS_SECRET_PROD}
            BUCKET_NAME_DEV: ${BUCKET_NAME_DEV}
            BUCKET_NAME_PROD: ${BUCKET_NAME_PROD}
            MINIO_BASE_URL_DEV: ${MINIO_BASE_URL_DEV}
            MINIO_BASE_URL_PROD: ${MINIO_BASE_URL_PROD}
            PORT_DEV: ${FLASK_PORT_DEV}
            PORT_PROD: ${FLASK_PORT_PROD}
            MINIO_CONNECTION_URL_DEV: ${MINIO_CONNECTION_URL_DEV}
            MINIO_CONNECTION_URL_PROD: ${MINIO_CONNECTION_URL_PROD}
        build:
            context: .
            dockerfile: flask.dockerfile
        networks:
            - healthcare
        ports:
            - "6500:${FLASK_PORT}"

networks:
    healthcare:
